# Generated by Django 5.0.7 on 2024-08-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='group_chat',
            new_name='room',
        ),
    ]
